### ISSUE TITLE
Error while compiling with --aot flag

### ISSUE THREAD

**Issue by Deep-Winter** [axented/ngx-icons#1]
ERROR in Error at C:/MyProject/node_modules/ngx-icons/dist/themify-icons/themify.component.d.ts.ThemifyComponent.html(2,11): Property 'name' is private and only accessible within class 'ThemifyComponent'.

Please fix this! Thank you :-)

**Comment by rodgc** [comment]
Hi @Deep-Winter 
Thank you for sending us this error,  it's fixed now

**Comment by Deep-Winter** [comment]
Perfect! Thank you!
